import json
import os
from pathlib import Path

from .fingerprint import (
    CONFIG_HASH_LABEL,
    IDENTITY_HASH_LABEL,
    chain_config_hash,
    chain_identity_hash,
)
from .models import Chain, DockerNetwork


INTERNAL_PORTS = {
    "rpc": 26657,
    "rest": 1317,
    "grpc": 9090,
    "evm_rpc": 8545,
    "evm_ws": 8546,
}


def _quoted(value: object) -> str:
    return json.dumps(str(value))


def _render_chain(chain: Chain) -> str:
    published_ports = (
        (chain.ports.rpc, INTERNAL_PORTS["rpc"]),
        (chain.ports.rest, INTERNAL_PORTS["rest"]),
        (chain.ports.grpc, INTERNAL_PORTS["grpc"]),
        (chain.ports.evm_rpc, INTERNAL_PORTS["evm_rpc"]),
        (chain.ports.evm_ws, INTERNAL_PORTS["evm_ws"]),
    )
    ports = "\n".join(f'      - "{host}:{container}"' for host, container in published_ports)
    return f"""  {chain.service}:
    image: xrplevm-local:dev
    build: *xrplevm-build
    command: [\"/bin/bash\", \"/app/local-node.sh\"]
    environment:
      CHAIN_ID: {_quoted(chain.chain_id)}
      MONIKER: {_quoted(chain.name)}
      CHAIN_NAME: {_quoted(chain.name)}
    labels:
      {CONFIG_HASH_LABEL}: {_quoted(chain_config_hash(chain))}
      {IDENTITY_HASH_LABEL}: {_quoted(chain_identity_hash(chain))}
    ports:
{ports}
    networks:
      xrplevm_net:
        ipv4_address: {chain.ip}
    volumes:
      - {chain.volume}:/app/.exrpd
    healthcheck:
      test: [\"CMD-SHELL\", \"curl -fsS http://localhost:26657/status >/dev/null || exit 1\"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 20s
"""


def compose_text(chains: tuple[Chain, ...], network: DockerNetwork, build_context: str = "..") -> str:
    services = "\n".join(_render_chain(chain) for chain in chains)
    volumes = "\n".join(f"  {chain.volume}:" for chain in chains)
    return f"""# Generated by src/main.py. Do not edit manually.
x-xrplevm-build: &xrplevm-build
  context: {_quoted(build_context)}
  dockerfile: docker/Dockerfile

services:
{services}
networks:
  xrplevm_net:
    name: {_quoted(network.name)}
    external: true

volumes:
{volumes}
"""


def render_compose(
    output_file: Path,
    chains: tuple[Chain, ...],
    network: DockerNetwork,
) -> Path:
    output_file = output_file.resolve()
    output_file.parent.mkdir(parents=True, exist_ok=True)
    root_dir = Path(__file__).resolve().parents[2]
    build_context = Path(os.path.relpath(root_dir, output_file.parent)).as_posix()
    output_file.write_text(compose_text(chains, network, build_context), encoding="utf-8")
    return output_file
